<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// no need auth
Route::get('/', 'IndexController@index')->name('index');

// auth controller (login & register), generated by laravel
Auth::routes();

// all routes below need auth
Route::middleware('auth')->group(function () {
    Route::get('home', 'HomeController@index')->name('home');
    Route::get('kitchen', 'IndexController@kitchen')->name('kitchen');
    
    Route::get('order', 'OrderController@index')->name('order');
    Route::get('order/detail/{id}', 'OrderController@show')->name('order.detail');
    Route::get('order/create', 'OrderController@create')->name('order.create');
    Route::post('order/save', 'OrderController@store')->name('order.store');
    Route::delete('order/delete/{id}', 'OrderController@destroy')->name('order.delete');
    Route::get('order/add-to-cart/{id}', 'OrderController@addToCart')->name('order.add-to-cart');
    Route::get('order/update-cart', 'OrderController@updateCart')->name('order.update-cart');
    Route::get('order/remove-from-cart', 'OrderController@removeFromCart')->name('order.remove-from-cart');
    Route::get('order/empty-cart', 'OrderController@emptyCart')->name('order.empty-cart');
    
    // all route below use '/admin/{url}' and can only be accessed by role admin/owner
    Route::group(['prefix' => 'admin', 'middleware' => ['role']], function(){
        // dashboard
        Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

        // transaction
        Route::get('transaction', 'TransactionController@index')->name('admin.transaction');

        // product
        Route::get('product', 'ProductController@index')->name('admin.product');
        Route::get('product/detail/{id}', 'ProductController@show')->name('admin.product.detail');
        Route::get('product/create', 'ProductController@create')->name('admin.product.create');
        Route::post('product/save', 'ProductController@store')->name('admin.product.store');
        Route::delete('product/delete/{id}', 'ProductController@destroy')->name('admin.product.delete');

        // user
        Route::get('user', 'UserController@index')->name('admin.user');
        Route::get('user/detail/{id}', 'UserController@show')->name('admin.user.detail');
        Route::get('user/create', 'UserController@create')->name('admin.user.create');
        Route::post('user/save', 'UserController@store')->name('admin.user.store');
        Route::delete('user/delete/{id}', 'UserController@destroy')->name('admin.user.delete');

        // category
        Route::get('category', 'CategoryController@index')->name('admin.category');

        Route::get('category/product', 'CategoryController@indexProduct')->name('admin.category.product');
        Route::get('category/product/create', 'CategoryController@createProduct')->name('admin.category.create.product');

        Route::get('category/payment', 'CategoryController@indexPayment')->name('admin.category.payment');
        Route::get('category/payment/create', 'CategoryController@createPayment')->name('admin.category.create.payment');

        Route::get('category/ordertype', 'CategoryController@indexOrderType')->name('admin.category.ordertype');
        Route::get('category/ordertype/create', 'CategoryController@createOrderType')->name('admin.category.create.ordertype');
        
        Route::get('category/detail/{id}', 'CategoryController@show')->name('admin.category.detail');
        Route::post('category/save', 'CategoryController@store')->name('admin.category.store');
        Route::delete('category/delete/{id}', 'CategoryController@destroy')->name('admin.category.delete');

        // customer
        Route::get('customer', 'CustomerController@index')->name('admin.customer');
        
        // coupon
        Route::get('coupon', 'CouponController@index')->name('admin.coupon');

        // config
        Route::get('config', 'ConfigController@index')->name('admin.config');
        Route::post('config/save', 'ConfigController@store')->name('admin.config.save');
    });
});
